# Generated by Django 4.2 on 2023-09-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
